### ISSUE TITLE
Criando uma aplicação (Internet Banking) com Angular 6 — na prática e sem complicações parte 2

### ISSUE THREAD

**Issue by mmalaquiasdev** [training-center/editorial#1]
Esse artigo é um draft, então porfavor quem revisar se atentar em programar uma data de publicação seguindo o padrão que definimos

**Comment by mmalaquiasdev** [comment]
Issue marcada com label de **attention** por estar 7 dias em andamento.

Vamos láaaaa, falta pouquinho pra gente publicar!! \o/

**Comment by laurenmariaferreira** [comment]
Artigo revisado. Fico no aguardo das correções para agendar. :D

**Comment by mmalaquiasdev** [comment]
fechado a issue pq  esse artigo já foi agendado 👍
