### ISSUE TITLE
Henrique Dal Bello submitted a story to Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#104]
Enviado na data: Mon, 17 Dec 2018 18:27:49 +0000 (UTC)

Novidades do C# 8.0: Ta saindo versão nova do forno! 💻 by Henrique Dal Bello Henrique Dal Bello submitted a story to Training Center for review. Please read the story and decide whether or not to

**Comment by malaquiasdev** [comment]
Já foi postado.
