### ISSUE TITLE
Luis Felipe Zaguini sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#110]
Enviado na data: Sun, 06 Jan 2019 22:00:42 +0000 (UTC)

Sobre testes de software: Uma visão um pouco mais aprofundada e razoável sobre testes by Luis Felipe Zaguini Luis Felipe Zaguini submitted a draft to Training Center and is waiting for you to review it

**Comment by malaquiasdev** [comment]
Artigo revisado e agendado para segunda-feira dia 14.
