### ISSUE TITLE
Hugo Costa submitted a story to Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#111]
Enviado na data: Tue, 08 Jan 2019 16:35:47 +0000 (UTC)

Introdução REST: Ao contrário de que muitos pensam, REST não tem nada haver com descansar (rest em inglês ). REST são siglas para Representational State… by Hugo Costa Hugo Costa submitted a story to

**Comment by larien** [comment]
Esse post já foi marcado como publicado no Medium do TC, pssoas

Sabem dizer quem fez a revisão?

**Comment by malaquiasdev** [comment]
fechando isso, o @khaosdoctor moveu para publicado.
