### ISSUE TITLE
Luis Felipe Zaguini submitted a story to Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#112]
Enviado na data: Thu, 10 Jan 2019 10:25:35 +0000 (UTC)

Sobre testes de software: Uma visão um pouco mais aprofundada e razoável sobre testes by Luis Felipe Zaguini Luis Felipe Zaguini submitted a story to Training Center for review. Please read the story

**Comment by malaquiasdev** [comment]
@laurenmariaferreira esse texto, não ta mais na nossa lista... vc publicou ele?

**Comment by larien** [comment]
Esqueci de alterar o status aqui no board. Mal aí, clã!
