### ISSUE TITLE
Fernando Almeida sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#113]
Enviado na data: Thu, 10 Jan 2019 13:45:42 +0000 (UTC)

Boas práticas REST: indo além do código: Quando iniciamos um projeto atualmente e adotamos a composição em módulos, é comum considerarmos a utilização de microsserviços, seja pela… by Fernando Almeida

**Comment by malaquiasdev** [comment]
artigo foi publicado.
