### ISSUE TITLE
Kirmayr Tomaz sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#12]
Enviado na data: Thu, 26 Jul 2018 16:38:31 +0000 (UTC)

De onde vem a felicidade dentro do trabalho?: Você está bem ? Como está se sentindo ? by Kirmayr Tomaz Kirmayr Tomaz submitted a draft to Training Center and is waiting for you to review it. You can

**Comment by mmalaquiasdev** [comment]
link do draft: https://medium.com/@kirmayrtomaz/225c8247353f

**Comment by mmalaquiasdev** [comment]
Processo de revisão em andamento, parei no tópico **"Seja verdadeiro"**

**Comment by mmalaquiasdev** [comment]
Fechei a revisão desse artigo, agora é esperar o autor fazer ou não as devidas correções e seguir as sugestões.

**Comment by mmalaquiasdev** [comment]
artigo foi publicado :)
