### ISSUE TITLE
Validando regras de negócio em C# com specification pattern

### ISSUE THREAD

**Issue by larien** [training-center/editorial#133]
Regras para criação das issues de acompanhamento de artigos:

- coloque o título do artigo no título da issue
- coloque o link do artigo na issue
- não precisa escrever nada, basta colocar o link no template abaixo sobrescrevendo o *COLOCAR_O_LINK_AQUI* e apagar este cabeçalho
utilize as labels para sinalizar o status da review
---
Necessário fazer revisão no [artigo](https://medium.com/p/ba7b46630ef5/edit)

**Comment by malaquiasdev** [comment]
artigo publicado.
