### ISSUE TITLE
Validating business logic in C# with specification pattern

### ISSUE THREAD

**Issue by larien** [training-center/editorial#134]
Regras para criação das issues de acompanhamento de artigos:

- coloque o título do artigo no título da issue
- coloque o link do artigo na issue
- não precisa escrever nada, basta colocar o link no template abaixo sobrescrevendo o *COLOCAR_O_LINK_AQUI* e apagar este cabeçalho
utilize as labels para sinalizar o status da review
---
Necessário fazer revisão no [artigo](https://medium.com/p/35dfe9593856/edit)

**Comment by malaquiasdev** [comment]
artigo publicado.
