### ISSUE TITLE
Giovanni Cruz sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#15]
Enviado na data: Fri, 27 Jul 2018 21:20:16 +0000 (UTC)

Comece por aqui!: Olá! Meu nome é Giovanni Cruz, sou Desenvolvedor Fullstack, tenho 21 anos e sou mentor no Training Center, atualmente. Seja bem-vindo ao… by Giovanni Cruz Giovanni Cruz submitted a

**Comment by woliveiras** [comment]
Eita! Só se ele removeu da publicação, mano.

**Comment by mmalaquiasdev** [comment]
Então é **close!**
