### ISSUE TITLE
Inteligência artificial (para não desenvolvedores) alavancando resultados para empresas

### ISSUE THREAD

**Issue by mmalaquiasdev** [training-center/editorial#16]
Necessário fazer revisão [Inteligência artificial (para não desenvolvedores) alavancando resultados para empresas](https://medium.com/@cleisoncarlos/intelig%C3%AAncia-artificial-para-n%C3%A3o-desenvolvedores-alavancando-resultados-para-empresas-94b889b3c670I).

OBS: Esse artigo já veio como publicado então não temos como agendar suas publicações, apenas revisar, não precisamos aguardar as ponderações do autor(a).

**Comment by laurenmariaferreira** [comment]
Artigo revisado.
