### ISSUE TITLE
Uma análise sobre a Engenharia do Conhecimento

### ISSUE THREAD

**Issue by mmalaquiasdev** [training-center/editorial#17]
Necessário fazer revisão [Uma análise sobre a Engenharia do Conhecimento](https://medium.com/@cleisoncarlos/precisamos-compartilhar-uma-an%C3%A1lise-sobre-a-engenharia-do-conhecimento-77936937afee).

OBS: Esse artigo já veio como publicado então não temos como agendar suas publicações, apenas revisar, não precisamos aguardar as ponderações do autor(a).

**Comment by laurenmariaferreira** [comment]
Artigo revisado.
