### ISSUE TITLE
Ricardo Gosch sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#19]
Enviado na data: Fri, 03 Aug 2018 00:06:44 +0000 (UTC)

A Música e sua ligação direta com a Produtividade: Sabemos que a música tem um grande efeito no nosso psicológico, e por que não usarmos deste artifício de tão fácil acesso para aumentar… by Ricardo

**Comment by laurenmariaferreira** [comment]
Artigo revisado e aguardando correções.

**Comment by laurenmariaferreira** [comment]
Correções feitas, aguardando autor inserir capa no artigo.

**Comment by mmalaquiasdev** [comment]
@laurenmariaferreira consegue dar alguma indicação de capa pra ele? 

eu catei algumas capas aqui que achei interessante sobre o tópico dele:

1. http://novo.hr/wp-content/uploads/2017/09/ured-slu%C5%A1anje-glazbe-pixabay.jpg

2. https://images.fastcompany.net/image/upload/w_1280,f_auto,q_auto,fl_lossy/fc/3063730-poster-p-1-how-music-improves-the-workflow-in-your-office.jpg

3. http://www.kohajone.com/wp-content/uploads/2017/09/16-workplace-stress-music.jpg

**Comment by laurenmariaferreira** [comment]
Mandei pra ele, moço, obrigada pelo help
Ele tava querendo com fotógrafos indepentes, tho :| vamos ver se ele curte alguma

**Comment by woliveiras** [comment]
@rgosch podemos colocar alguma capa no seu artigo pra já agendarmos?

**Comment by ohgosch** [comment]
@woliveiras tenho como objetivo usar foto de fotógrafos(as) independentes e de baixa renda. Tá bem difícil de achar, mas seguirei firme.

Vocês tem alguma sugestão?

**Comment by larien** [comment]
Sucesso na missão, pssoas! Artigo agendado para dia 10 :)
