### ISSUE TITLE
Livia Gabos

### ISSUE THREAD

**Issue by mmalaquiasdev** [training-center/editorial#21]
Contatos:

Telegram: @liviagabos 
Twitter: @liviagabos

**Comment by mmalaquiasdev** [comment]
Email enviado, aguardando resposta :)

**Comment by mmalaquiasdev** [comment]
Estou entrevistando a Livia pelo telegram, a abordagem por email não foi muito interessante.

**Comment by mmalaquiasdev** [comment]
Dei um pause de algumas horas com a Livia pra poder focar na #31, mas devo voltar a seguir na segunda-feira com ela

**Comment by malaquiasdev** [comment]
Dado que a entrevista esta chegando no fim (falta praticamente 1 pergunta) vou começar a redigir o artigo pro Medium

**Comment by malaquiasdev** [comment]
Estou escrevendo o artigo ao poucos devido a falta de tempo, mas não ta parado.

**Comment by malaquiasdev** [comment]
Voltei a escrever! Entrevista em andamento

**Comment by malaquiasdev** [comment]
Preciso terminar de transcrever o artigo da Livia, meu pai do céu!

**Comment by malaquiasdev** [comment]
O artigo já esta no medium, a Livia já deu uma revisada e agora eu preciso conseguir ajustar pra poder mandar o draft.

Mas essa semana to sem tempo, por isso o with problems
