### ISSUE TITLE
Juliana Dias dos Santos Silva

### ISSUE THREAD

**Issue by mmalaquiasdev** [training-center/editorial#26]
Contatos:

Telegram:  @juuh42dias 
Twitter: https://twitter.com/juuh42dias

**Comment by mmalaquiasdev** [comment]
email enviado, aguardando resposta 👍

**Comment by malaquiasdev** [comment]
issue fechada durante a limpeza de contatos para entrevista

**Comment by juuh42dias** [comment]
Olá @malaquiasdev consegue alterar o título da issue removendo o nome completo por favor?

**Comment by malaquiasdev** [comment]
@juuh42dias, claro! removi o nome :)
