### ISSUE TITLE
PHP Básico — Construtores da Linguagem e Funções

### ISSUE THREAD

**Issue by mmalaquiasdev** [training-center/editorial#3]
Artigo já veio como publicado, aí não tem o que fazer, é revisar e publicar.

**Comment by laurenmariaferreira** [comment]
Artigo revisado. Como alguns erros foram apontados, vou aguardar o autor corrigi-los antes de publicar o artigo no TC.

**Comment by laurenmariaferreira** [comment]
Artigo revisado e corrigido pelo autor.
