### ISSUE TITLE
 Cuducos 

### ISSUE THREAD

**Issue by mmalaquiasdev** [training-center/editorial#31]
Contato:

Twitter: https://twitter.com/cuducos
Telegram: @cuducos

**Comment by mmalaquiasdev** [comment]
Já fiz a entrevista com ele e agora estou formatando tudo em um artigo para o medium :)

**Comment by mmalaquiasdev** [comment]
90% da entrevista já foi transpilada p/ um texto do Medium e enviei para revisão.

**Comment by khaosdoctor** [comment]
Revisei o artigo aqui, já corrigi as anotações que ele fez e está agendado para segunda 03/09 as 11h30
