### ISSUE TITLE
Miguel Soares

### ISSUE THREAD

**Issue by mmalaquiasdev** [training-center/editorial#33]
Contatos:

**Comment by mmalaquiasdev** [comment]
email enviado.

**Comment by malaquiasdev** [comment]
Entrei em contato com a Miguel pelo telegram

**Comment by malaquiasdev** [comment]
Topou participar pelo telegram e estou aguardando a primeira resposta

**Comment by malaquiasdev** [comment]
entrevista cancelada, devido a demora da participante em responder.
