### ISSUE TITLE
Software Developers: the chaos is your workspace!

### ISSUE THREAD

**Issue by mmalaquiasdev** [training-center/editorial#5]
Artigo já veio como publicado.

**Comment by laurenmariaferreira** [comment]
Mandei mensagem para o Vinicius perguntando sobre a versão em português do texto.

**Comment by laurenmariaferreira** [comment]
Enviei outro comentário perguntando sobre a versão em português. Aguardando resposta.

**Comment by larien** [comment]
O escritor disse que está traduzindo aos poucos, pois está bem ocupado. Me disponibilizei para traduzir por ele. Vamos ver o que ele acha :D

**Comment by jcserracampos** [comment]
@laurenmariaferreira algum update?

**Comment by larien** [comment]
Opa! Desculpa a demora, não tinha visto hahaha
Mandei mensagem para o Vinicius perguntando sobre. Ele não havia respondido sobre a tradução ainda.

**Comment by larien** [comment]
Temos notícias! Como ele tá cheio de coisa pra fazer e eu não (zoas) vou continuar a tradução do artigo e publicar a versão em português :D

**Comment by larien** [comment]
Ele não respondeu mais e estou fechando a Issue até ter resposta novamente.
