### ISSUE TITLE
 Luiz Felipe Limeira 

### ISSUE THREAD

**Issue by mmalaquiasdev** [training-center/editorial#56]
Contato: https://twitter.com/lflimeira02

**Comment by khaosdoctor** [comment]
Eu enviei a entrevista pra ele já, vou marcar o @lflimeira aqui para que ele possa acompanhar a issue também

**Comment by mmalaquiasdev** [comment]
Coloquei como pausada devido ao tempo na mesma situação, mas vamos aproveitar esse momento para reiniciar tentando um jeito diferente

**Comment by lflimeira** [comment]
Seus lindos, como vai ser um novo formato? Vacilo meu pela demora. =(

**Comment by malaquiasdev** [comment]
@lflimeira assim que eu fechar a da @liviagabos eu colo em vc!

**Comment by malaquiasdev** [comment]
Entrei em contato pelo telegram pra dar seguimento a entrevista

**Comment by khaosdoctor** [comment]
Eu já falei com o @lflimeira vamos dar continuidade entre amanhã e quarta na entrevista :) já estamos com as paradas todas criadas

**Comment by malaquiasdev** [comment]
toquem o barco, amo vcs S2

**Comment by malaquiasdev** [comment]
Alguma novidade gente?

**Comment by lflimeira** [comment]
@mmalaquiasdev estamos fazendo async, ja tem bastante conteúdo =)

**Comment by khaosdoctor** [comment]
Já finalizamos aqui, está no Medium para revisão https://medium.com/trainingcenter/como-%C3%A9-trabalhar-como-desenvolvedor-backend-por-luiz-felipe-limeira-f795edc4fe48

**Comment by malaquiasdev** [comment]
Como já chegou pra revisão, vamos fechar essa issue aqui :)
