### ISSUE TITLE
Criando meu site pessoal — Parte 1

### ISSUE THREAD

**Issue by laurenmariaferreira** [training-center/editorial#6]
[Link para revisão](https://medium.com/trainingcenter/criando-meu-site-pessoal-parte-1-4abf417c56d8)
Revisem com carinho, por favor <3 esse artigo tava parado há uns 4 meses UHFAUEFHAHUL

**Comment by mmalaquiasdev** [comment]
:) vou pegar pra revisar.

**Comment by mmalaquiasdev** [comment]
Revisado, fiz poucas sugestões, esse aqui parece o mais promissor pra ser publicado na quarta-feira, mesmo se as sugestões não forem aderidas a tempo.

Ta programado pra se publicado as 10:30
