### ISSUE TITLE
Rafael Soares sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#61]
Enviado na data: Sun, 19 Aug 2018 11:44:11 +0000 (UTC)

Guia para armazenar as senhas no banco de dados de forma decente e segura: Antes: se você é mais de vídeo do que de texto, o conteúdo deste artigo está todo aqui: https://youtu.be/HMrffmy9DIQ by Rafael

**Comment by mmalaquiasdev** [comment]
O artigoi foi publicado pelo autor, então apareceu como outra issue p/ gente
