### ISSUE TITLE
Rafael Soares submitted a story to Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#63]
Enviado na data: Wed, 22 Aug 2018 22:11:33 +0000 (UTC)

Guia para armazenar senhas no banco de dados de forma decente e segura: E antes de falar sobre como armazenar as senhas, vamos explorar algumas formas de se quebrar senhas já em forma de hash. by

**Comment by mmalaquiasdev** [comment]
Vou tocar a revisão desse artigo aqui, ele já veio como publicado, então só vou fazer as ponderações e publicar.

**Comment by mmalaquiasdev** [comment]
link de acesso pra facilitar a revisão: https://medium.com/@rafaels88/guia-para-armazenar-senhas-no-banco-de-dados-de-forma-decente-e-segura-197d1d9ab43a

**Comment by malaquiasdev** [comment]
terminei a revisão do texto, como ele já veio como publicado, não da pra agendar, então já mandei ver :)
