### ISSUE TITLE
Danilo Agostinho sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#64]
Enviado na data: Fri, 24 Aug 2018 01:32:17 +0000 (UTC)

Criando uma aplicação (Internet Banking) com Angular 6 — na prática e sem complicações parte 3: Salve pessoal! by Danilo Agostinho Danilo Agostinho submitted a draft to Training Center and is waiting

**Comment by larien** [comment]
Artigo revisado e aguardando correções.

**Comment by larien** [comment]
Artigo revisado e agendado para dia 7 :D
