### ISSUE TITLE
Matheus Castiglioni sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#70]
Enviado na data: Fri, 31 Aug 2018 19:03:02 +0000 (UTC)

Trabalhando com eventos no JavaScript: Imagine que temos um projeto em andamento, porém, precisamos adicionar uma nova funcionalidade em um de nossos componentes, hoje temos… by Matheus Castiglioni

**Comment by rafaels88** [comment]
Vou revisar esse!

**Comment by rafaels88** [comment]
Enviei as notes todas, esperando resposta do rapaz

**Comment by rafaels88** [comment]
Mandei uma mensagem pro Matheus em formato de note no título do artigo pra ver se ele vai conseguir ver as notes q deixei anteriormente. No aguardo pra agendar a publicação

**Comment by rafaels88** [comment]
O autor revisou as notes e agendei pro dia 24/09.
