### ISSUE TITLE
Felipe Limeira sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#72]
Enviado na data: Wed, 05 Sep 2018 14:54:20 +0000 (UTC)

Diário de um dev na estrada — A preparação: Eae galera, estou aqui mais uma vez, agora para falar da experiência mais incrível que eu tive e como foi todo o processo de preparação… by Felipe Limeira

**Comment by jcserracampos** [comment]
Da minha parte, revisado.

**Comment by malaquiasdev** [comment]
@jcserracampos move ela pra 'Review done' pae :)
