### ISSUE TITLE
Walmyr Carvalho

### ISSUE THREAD

**Issue by rafaels88** [training-center/editorial#73]
Contato: https://twitter.com/walmyrcarvalho

**Comment by rafaels88** [comment]
Entrei em contato com ele, esperando a resposta.

**Comment by malaquiasdev** [comment]
@rafaels88 Alguma novidade man? 
Se não conseguiu dar um start com tantos dias que tal cancelar essa tentativa e tentar outra pessoa?

**Comment by rafaels88** [comment]
Desculpa a demora =/ me enrolei muito com outras coisas.

Maaas, mandei as perguntas pra ele hoje, to esperando resposta o/

**Comment by malaquiasdev** [comment]
Nada?

**Comment by rafaels88** [comment]
Nada ainda =/ ele chegou a me responder dizendo q ia tentar me entregar tudo essa semana, mas realmente não tenho certeza

**Comment by rafaels88** [comment]
Gente, vou pausar isso aqui. Nao recebi nada. Vou pular pra proxima.

#peace

**Comment by malaquiasdev** [comment]
Vamos re-abrir quando surgir uma resposta :)
