### ISSUE TITLE
Livia Gabos sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#75]
Enviado na data: Wed, 12 Sep 2018 00:32:16 +0000 (UTC)

Depois de quase 30 anos descobri que sou negra.: Esse título apesar de parecer click bait, não é. Infelizmente. by Livia Gabos Livia Gabos submitted a draft to Training Center and is waiting for you to

**Comment by larien** [comment]
Artigo revisado. Aguardando correções.

**Comment by malaquiasdev** [comment]
O artigo foi publicado
