### ISSUE TITLE
Mikael Hadler sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#76]
Enviado na data: Mon, 17 Sep 2018 22:33:28 +0000 (UTC)

Git flow as control system version: This article intends to expose a flow flow utilization approach. by Mikael Hadler Mikael Hadler submitted a draft to Training Center and is waiting for you to review

**Comment by rafaels88** [comment]
Vou revisar esse artigo hj. Assim q eu mandar as notes eu troco a label

**Comment by rafaels88** [comment]
Enviei as notes, esperando resposta.

**Comment by rafaels88** [comment]
Ele já respondeu e eu agendei pra Sep 26, 2018.
