### ISSUE TITLE
Cristiano Gonçalves sent a draft to Training Center for review

### ISSUE THREAD

**Issue by jcserracampos** [training-center/editorial#77]
Enviado na data: Mon, 17 Sep 2018

Entendendo affordance na prática. by Crisitano Gonçalves
Cristiano Gonçalves submitted a draft to Training Center and is waiting for you to review

**Comment by rafaels88** [comment]
Esse draft aparentemente não tá mais disponível no Medium

**Comment by rafaels88** [comment]
Só pra facilitar, essa publicação já tá publicada: https://medium.com/trainingcenter/entendendo-affordance-na-pr%C3%A1tica-f41ec34dff2 . 

Se ninguém pegar até sexta eu posso pegar.

**Comment by rafaels88** [comment]
Como já está publicada, estou fechando.
