### ISSUE TITLE
Ruan Victor sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#79]
Enviado na data: Mon, 24 Sep 2018 20:30:20 +0000 (UTC)

Usando os Pull Request a favor do time: Você chega em uma equipe, começa a utilizar o Git e chega o grande momento: revisar o pull request (PR) de alguém ou submeter um PR para… by Ruan Victor Ruan

**Comment by malaquiasdev** [comment]
Link do artigo p/ ajudar:

https://medium.com/@ruan.victor/777379bb11a

**Comment by jcserracampos** [comment]
Revisarei este

**Comment by jcserracampos** [comment]
Revisado e agendado para sexta-feira.

**Comment by jcserracampos** [comment]
Publicado.
https://medium.com/trainingcenter/usando-os-pulls-requests-a-favor-do-time-777379bb11a
