### ISSUE TITLE
Algumas dicas valiosas para estudantes desesperados

### ISSUE THREAD

**Issue by larien** [training-center/editorial#80]
https://medium.com/p/f644313f4ff4/edit

**Comment by rafaels88** [comment]
Ja veio publicado. Como o gabriel veio falar direto comigo no Slack do TC, já editei as tags e aceitei o artigo.

**Comment by rafaels88** [comment]
Maas, fica a vontade pra mandar alguma note o/

**Comment by larien** [comment]
Tranquilo, moço o/ vou mandar algumas notes, sim. Mas antes de manipular os artigos, altera (ou cria) a issue pra gente manter o controle :D

**Comment by rafaels88** [comment]
Eitcha, my bad total! Mas a issue não foi criada quando ele mandou o artigo? Eu vacilei e não dei o assign antes, confesso que achei que todo mundo tivesse dormindo a essa hora hahaha mas você tá no mesmo timezone que eu.

Não acontecerá de novo!

**Comment by larien** [comment]
Eeeeeeeei, relaxa! Fica tranquilo hahaha
As vezes esse negócio de issues falha e não é criada assim que a pessoa envia para a gente. Se não me engano, isso acontece especialmente cm artivos já publicados, pois o plugin de automatização foi feito para drafts e os published foram excluídos dessa hihihi

**Comment by jcserracampos** [comment]
A issue foi criada depois porque a @laurenmariaferreira foi mais rápida 😆

**Comment by larien** [comment]
CONFIA NO GATILHO RAPÁ

**Comment by larien** [comment]
Só para reforçar: não é necessário deixar notes no artigo que já veio como publicado
Eu só deixei porque o autor ainda estava online quando comecei a ler o texto
E também porque eu sô rebelde

**Comment by malaquiasdev** [comment]
issue fechada, o artigo já foi publicado.
