### ISSUE TITLE
Gabriel Santos submitted a story to Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#81]
Enviado na data: Mon, 01 Oct 2018 11:24:39 +0000 (UTC)

Algumas dicas valiosas para estudantes desesperados: Você, pessoa desenvolvedora (ou que pretende se tornar uma), já sentiu desespero por ter tanta coisa pra estudar? Ou simplesmente estuda… by Gabriel

**Comment by jcserracampos** [comment]
Duplicado.
