### ISSUE TITLE
Samuel Monteiro sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#85]
Enviado na data: Fri, 05 Oct 2018 19:18:52 +0000 (UTC)

Construindo uma aplicação Full-Stack com React: Parte 1: Criando a API com Node e Express by Samuel Monteiro Samuel Monteiro submitted a draft to Training Center and is waiting for you to review it.

**Comment by malaquiasdev** [comment]
link para o artigo https://medium.com/@samuelmonteiro/c1a64db6fc94

**Comment by malaquiasdev** [comment]
Como tinham poucos erros para serem corrigidos, eu publiquei o texto.

https://medium.com/trainingcenter/construindo-uma-aplicação-full-stack-com-react-c1a64db6fc94
