### ISSUE TITLE
Danilo Agostinho sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#87]
Enviado na data: Sat, 20 Oct 2018 01:47:01 +0000 (UTC)

Criando uma aplicação (Internet Banking) com Angular 6 — na prática e sem complicações parte 4: Salve pessoal! Chegamos a parte 4 da nossa série de posts para o Training Center. Caso tenha perdido a

**Comment by larien** [comment]
Artigo corrigido e agendado para 29 de outubro às 11:30.
