### ISSUE TITLE
Lucas Santos sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#88]
Enviado na data: Sun, 21 Oct 2018 15:42:27 +0000 (UTC)

Como by Lucas Santos Lucas Santos submitted a draft to Training Center and is waiting for you to review it. You can leave notes, make edits, and publish the story when it&#39;s ready. Como Lucas Santos

**Comment by malaquiasdev** [comment]
Artigo já está agendado para hoje.
