### ISSUE TITLE
Eduardo Figueiredo Gonçalves submitted a story to Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#91]
Enviado na data: Sun, 11 Nov 2018 14:30:36 +0000 (UTC)

TDD: Estava estudando um pouco sobre TDD esses dias e vi o artigo que me fez pensar em algumas coisas interessantes e resolvi escrever esse… by Eduardo Figueiredo Gonçalves Eduardo Figueiredo Gonçalves

**Comment by malaquiasdev** [comment]
artigo já foi publicado
