### ISSUE TITLE
Eduardo Figueiredo Gonçalves submitted a story to Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#92]
Enviado na data: Tue, 13 Nov 2018 01:41:34 +0000 (UTC)

TDD: Iniciando com TDD no PHP: TDD by Eduardo Figueiredo Gonçalves Eduardo Figueiredo Gonçalves submitted a story to Training Center for review. Please read the story and decide whether or not to

**Comment by malaquiasdev** [comment]
Artigo já foi publicado
