### ISSUE TITLE
Cristiano Gonçalves sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#94]
Enviado na data: Sun, 25 Nov 2018 13:10:08 +0000 (UTC)

Entendendo semiótica na prática: A semiótica está presente em diversas áreas do conhecimento, como design, psicologia, filosofia e etc. Nesse artigo irei mostrar como a… by Cristiano Gonçalves

**Comment by malaquiasdev** [comment]
Peguei esse artigo para revisar.

https://medium.com/@kristiano.gon/51ed8e84b7f5

**Comment by malaquiasdev** [comment]
Bom eu finalmente comecei a revisão desse artigo, to planejando postar ele na sexta-feira. Porque a escrita está muito boa, já estou na metade e tem pouca coisa para se arrumar.

**Comment by malaquiasdev** [comment]
A revisão foi fechada, estou esperando o Cristiano Gonçalves me responder dizendo se a gente consegue publicar na sexta.

Ele dizendo que sim, já coloco um agendamento.

**Comment by malaquiasdev** [comment]
O texto foi agendado para amanhã as 10h, então estou fechando essa issue.
