### ISSUE TITLE
Felipe Limeira sent a draft to Training Center for review

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#95]
Enviado na data: Mon, 26 Nov 2018 22:02:32 +0000 (UTC)

Testes E2E no JavaScript com Cypress.io — APIs: Fala pessoal, tudo tranquilo? No meu ultimo artigo sobre Cypress.io eu mostrei como realizar testes e2e com interações em interfaces… by Felipe Limeira

**Comment by malaquiasdev** [comment]
Artigo já tinha sido revisado por mim, antes de ele conseguir enviar o draft e já publiquei ontem mesmo.
