### ISSUE TITLE
Ricardo Gouveia submitted a story to Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/editorial#98]
Enviado na data: Wed, 28 Nov 2018 08:41:19 +0000 (UTC)

User Agent Style Sheet: o porquê de um CSS que só serve para ser sobrescrito: Reflexão sobre o passado, o presente eo futuro do CSS embutido no browser, do ponto de vista do desenvolvedor. by Ricardo

**Comment by malaquiasdev** [comment]
Link do artigo para ajudar:

https://medium.com/@ricardogouveia3/user-agent-style-sheet-o-porqu%C3%AA-de-um-css-que-s%C3%B3-serve-para-ser-sobrescrito-f1ef84c9ebf7

**Comment by malaquiasdev** [comment]
Revisado e publicado. O artigo já veio publicado pelo autor.
